### ISSUE TITLE
External Events section links to missing section on docs.github.com

### ISSUE THREAD

**Issue by nschonni** [repo-sync/repo-sync#22]
Currently the link https://help.github.com/en/articles/events-that-trigger-workflows#external-events doesn't resolve to any heading on that document.
I'm guessing it may be referring to something that would use https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#repository_dispatch or https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch, but some details would be helpful

**Comment by wei** [comment]
https://docs.github.com/en/actions/reference/events-that-trigger-workflows#manual-events should probably work. PR welcome
