### ISSUE TITLE
One-way repo-sync?

### ISSUE THREAD

**Issue by JensHaley** [repo-sync/repo-sync#28]
Hi there,

the [README](https://github.com/repo-sync/repo-sync/blob/master/README.md) says in section _Features_ that one-way syncs are possible, but this case is not mentioned on the rest of the page.

What would I have to do for a one-way sync? Just adding the workflow file in one repo does not seem to work.

Thanks

**Comment by wei** [comment]
Just adding it to one repo should work. Please let us know what kind of issues you're having.

**Comment by JensHaley** [comment]
Thanks for the quick reply - don't know why I got the impression I need to set up the workflows in two repos.

Created this PR to give others a hint on this:
https://github.com/repo-sync/repo-sync/pull/29

Closing this issue...
