### ISSUE TITLE
guidance: Your two repos must share a commit history.

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [repo-sync/repo-sync#32]
The README mentions:
> Your two repos must share a commit history.

I'm confused as to how to set this up exactly; could you provide some details/help for this? Especially for two repos that are already setup (and have commits in them) - I'd love to know how to integrate this to get my repos syncing.

Thanks

**Comment by wei** [comment]
Something like this might work for you: https://gist.github.com/msrose/2feacb303035d11d2d05
